### ISSUE TITLE
(oopsP) throw new Error('Invalid configuration')

### ISSUE THREAD

**Issue by DJay-X** [homespun/homebridge-accessory-bandwidth-quality#2]
I finally was able to install the Plugin again, now  (v.0.2.0).
With a config.json that is valid "jsonlint.com", I still get an error and homebridge crashes.

Thanks again for your help and work.

     {
            "accessory": "bandwidth-quality",
            "name": "Internet Bandbreite",
            "token": "xxxxxxxx",
            "nominal": {
                "units": "Mbps",
                "value": 300
            },
            "options": {
                "ttl": 1800
            }
        }

```
Okt 15 22:46:07 raspberrypi homebridge[4868]: [2018-10-15 22:46:07] Loading 2 accessories...
Okt 15 22:46:07 raspberrypi homebridge[4868]: [2018-10-15 22:46:07] [Pi Zero Temp] Initializing RaspberryPiTemperature accessory...
Okt 15 22:46:07 raspberrypi homebridge[4868]: [2018-10-15 22:46:07] [Internet Bandbreite] Initializing bandwidth-quality accessory...
Okt 15 22:46:07 raspberrypi homebridge[4868]: /usr/local/lib/node_modules/homebridge-accessory-bandwidth-quality/index.js:54
Okt 15 22:46:07 raspberrypi homebridge[4868]:     if (oopsP) throw new Error('Invalid configuration')
Okt 15 22:46:07 raspberrypi homebridge[4868]:                      ^
Okt 15 22:46:07 raspberrypi homebridge[4868]: Error: Invalid configuration
Okt 15 22:46:07 raspberrypi homebridge[4868]:     at new BandwidthQuality (/usr/local/lib/node_modules/homebridge-accessory-bandwidth-quality/index.js:54:22)
Okt 15 22:46:07 raspberrypi homebridge[4868]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
Okt 15 22:46:07 raspberrypi homebridge[4868]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
Okt 15 22:46:07 raspberrypi homebridge[4868]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
Okt 15 22:46:07 raspberrypi homebridge[4868]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Okt 15 22:46:07 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Okt 15 22:46:07 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Okt 15 22:46:07 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by mrose17** [comment]
sorry! typo in the README. get the latest version and it will take your `config.json` file -- or -- change `"units"` to `"unit"` ... oops!

**Comment by DJay-X** [comment]
Awesome. Thanks @mrose17 
Works now!
![img_1803](https://user-images.githubusercontent.com/3874239/47158533-2b937900-d2ec-11e8-93e5-b65d2f22cf43.png)


Thanks for your great work and sharing here.
Looking forward to the ongoing development. Maybe with Upload and Ping included.

Thanks again .

**Comment by mrose17** [comment]
you're very welcome... the upload/ping statistics depend on the (excellent) underlying library that @branchard wrote... i'm planning on updating the homebridge plugin when the functionality is available!
