### ISSUE TITLE
Quality "Unknown" and Download Speed "0 Mbps"

### ISSUE THREAD

**Issue by DJay-X** [homespun/homebridge-accessory-bandwidth-quality#3]
Hi, I really hope not to bother. :) 
I noticed that the Quality often is "unknown" and the Speed is 0 Mbps from time to time.
Any Idea?

One thing I could imagine, if the actual speed is higher than the value in the config.json "unknown" is the result?
In my case value is 210 Mbps in the config but the history of the speedtest shows 2101 ?

Thanks again.

![napkin 19 10 18 9 18 10 am](https://user-images.githubusercontent.com/3874239/47203235-ea4ca900-d37f-11e8-93ce-c21306d93102.png)
![napkin 19 10 18 9 20 25 am](https://user-images.githubusercontent.com/3874239/47203337-3e578d80-d380-11e8-9941-f425d9dbf2fa.png)

```
  {
            "accessory": "bandwidth-quality",
            "name": "Internet Bandbreite",
            "token": "xxxxx",
            "nominal": {
                "unit": "Mbps",
                "value": 210
            },
            "options": {
                "ttl": 1800
            }
        }
```

**Comment by mrose17** [comment]
interesting. try the latest version `npm update -g homebridge-accessory-bandwidth-quality" and restart homekit. i've tried adding some sanity to the math... (-;

**Comment by DJay-X** [comment]
@mrose17 Thanks again. Love your work. Great you invest your time and brain in this.
All looks great. Can't wait to see ongoing development. 👍🏻

![napkin 20 10 18 1 42 12 pm](https://user-images.githubusercontent.com/3874239/47255238-f6af2f80-d46d-11e8-92a8-d495dd045e0b.png)

**Comment by mrose17** [comment]
thanks. a few things. the *real* list of credits is more like this: @pieceofsummer for reverse-engineering server-side HAP, @khaost for writing hap-nodejs that makes use of that work, @nfarina for writing homebridge that makes use of that work, @Seydx for writing a plugin that makes use of that work, @branchard for writing an npm module that makes use of the fast.com api. this plugin simply blends the work of the last two... cf., https://en.wikipedia.org/wiki/Standing_on_the_shoulders_of_giants (though i make no claim of seeing all that far)
